FROM node:16.13.2 AS react-build
WORKDIR /react-app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=react-build /react-app/build /usr/share/nginx/html

